- name: install prometheus
#  hosts: tag_Name_ec2_lab2_03032023
  hosts: prometheus
  remote_user: ec2-user
#  tasks:
#   - name: Ping my hosts
#     ansible.builtin.ping:
#   - name: Print message
#     ansible.builtin.debug:
#       msg: Hello world
  roles:
    - prometheus

- name: install node exporter
#  hosts: tag_Env_lab_ansible
  hosts: node-exporter
  remote_user: ec2-user
#  tasks:
#   - name: Ping my hosts
#     ansible.builtin.ping:
#   - name: Print message
#     ansible.builtin.debug:
#       msg: Hello world
  roles:
    - node-exporter

#- hosts: tag_Env_lab_ansible
#  tasks:
#    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
