- name: My first play
  hosts: tag_lab_ansible
  remote_user: ec2-user
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
  roles:
    - mysql
    #- prometheus
