#- name: install prometheus
#  hosts: tag_Name_ec2_lab2_03032023
##  remote_user: ec2-user
##  tasks:
##   - name: Ping my hosts
##     ansible.builtin.ping:
##   - name: Print message
##     ansible.builtin.debug:
##       msg: Hello world
#  roles:
#    - prometheus
#
##- name: install node exporter
##  hosts: tag_Env_lab_ansible
###  remote_user: ec2-user
###  tasks:
###   - name: Ping my hosts
###     ansible.builtin.ping:
###   - name: Print message
###     ansible.builtin.debug:
###       msg: Hello world
##  roles:
##    - node-exporter
#
##- hosts: tag_Env_lab_ansible
##  tasks:
##    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

---
- name: update and install prometheus
  hosts: tag_Name_ec2_lab2_03032023
  yum:
    name: prometheus
    state: latest
    update_cache: yes
#    cache_valid_time: 3600
#- name: prometheus args
#  template:
#    src: prometheus.j2
#    dest: /etc/default/prometheus
#    mode: 0644
#    owner: root
#    group: root
#  notify: restart_prometheus
#- name: prometheus configuration file
#  template:
#    src: prometheus.yml.j2
#    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
#    mode: 0755
#    owner: prometheus
#    group: prometheus
#  notify: reload_prometheus
#- name: start prometheus
#  systemd:
#    name: prometheus
#    state: started
#    enabled: yes