- name: install prometheus
  hosts: tag_Name_ec2_lab2_03032023
  remote_user: ec2-user
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
#  roles:
#    - node-exporter

- name: install node exporter
  hosts: tag_Env_lab_ansible
  remote_user: ec2-user
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
#  roles:
#    - node-exporter
